export const INITIAL_ENTITIES = [
    {
        x: 1,
        y: 1,
        h: 100,
        w: 50,
        dx: 0.4,
        dy: 0.8,
        color: 'red',
        id: '0',
    },
    {
        x: 580,
        y: 20,
        h: 50,
        w: 50,
        dx: 0.6,
        dy: 0.4,
        color: 'red',
        id: '1',
    },
    {
        x: 700,
        y: 200,
        h: 70,
        w: 90,
        dx: -0.1,
        dy: -0.1,
        color: 'red',
        id: '2',
    },
    {
        x: 400,
        y: 400,
        h: 50,
        w: 50,
        dx: 1,
        dy: -1,
        color: 'red',
        id: '3',
    },
    {
        x: 500,
        y: 100,
        h: 30,
        w: 150,
        dx: 0.8,
        dy: -0.6,
        color: 'red',
        id: '4',
    },
    {
        x: 150,
        y: 400,
        h: 80,
        w: 20,
        dx: -0.9,
        dy: 0.3,
        color: 'red',
        id: '5',
    },
    {
        x: 650,
        y: 500,
        h: 50,
        w: 50,
        dx: 1,
        dy: -0.95,
        color: 'red',
        id: '6',
    },
];
